 service: alami-node16-sqs-sns
 provider:
   name: aws
   runtime: nodejs16.x

   environment:
     SQS_URL:
       Ref: SQSQueue
     SNS_URL:
       Ref: SQSTopic

   iamRoleStatements:
     - Effect: Allow
       Action: "sqs:*"
       Resource:
         - Fn::GetAtt: [ SQSQueue, Arn]
     - Effect: Allow
       Action: "sns:*"
       Resource:
         Ref: SNSTopic

 resources:
   Resources:
     SQSQueue:
       Type: AWS::SQS::Queue
       Properties:
         QueueName: alami-node16-catalogItemsQueue
     SNSTopic:
       Type: AWS::SNS::Topic
       Properties:
         TopicName: alami-node16-createProductTopic
     SNSSubscription:
       Type: AWS::SNS::Subscription
       Properties:
         Endpoint:  alami181@mail.ru
         Protocol: email
         TopicArn:
           Ref: SNSTopic


 functions:
   catalogBatchProcess:
     handler: handler.catalogBatchProcess
     events:
       - http:
           path: users
           method: post
   usersInvite:
     handler: handler.usersInvite
     events:
       - sqs:
           batchSize: 2
           arn:
             Fn::GetAtt:
               - SQSQueue
               - Arn