service: alami-node16-sqs-sns
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin
  - 0 serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

  functions:
    token-authorizer:
      handler: handler.endpoint
      events:
        - http:
            type: token
            path: token
            method: get
            cors: true
            authorizer:
              name: tokenAuthorizer
              arn: "arn:aws:lambda:#{AWS::Region}:#{AWS:AccountId}:function:alami-rsaws7-auth-test-service-dev-tokenAuth"
              resultTtlInSeconds: method.request.header.Authorizztion
              identitySource: 0
    request-authorizer:
      handler: handler.endpoint
      events:
        - http:
            type: request
            path: request
            method: get
            cors: true
            authorizer:
              name: requestAuthorizer
              arn: "arn:aws:lambda:#{AWS::Region}:#{AWS:AccountId}:function:alami-rsaws7-auth-test-service-dev-requestAuth"
              resultTtlInSeconds: 0
              identitySource: method.request.querystring.token
